"use client";
import { FormEvent, useEffect, useRef, useState } from "react";

type Workflow={name:string;team:string;sessions:number;acceptance:number;status:string};
const initial:Workflow[]=[{name:"Lead summary",team:"Sales",sessions:450,acceptance:78,status:"Expand"},{name:"Reply draft",team:"Support",sessions:510,acceptance:75.7,status:"Investigate"},{name:"Feedback clustering",team:"Product",sessions:207,acceptance:65.9,status:"Watch"}];
const comparisonData:Record<string,{acceptance:[number,number];review:[number,number];read:string}>={"All workflows":{acceptance:[75.8,75.6],review:[12.9,13.6],read:"No meaningful overall acceptance change; workflow-level differences matter more."},"Lead summary":{acceptance:[77.3,78.2],review:[10.4,8.8],read:"Small directional improvement: acceptance rose while review flags fell."},"Reply draft":{acceptance:[76.8,77.0],review:[13.3,15.5],read:"Acceptance was flat, but review flags increased. Investigate before rollout."},"Feedback clustering":{acceptance:[66.7,65.7],review:[20.0,17.9],read:"Acceptance softened slightly while review flags declined; sample sizes remain small."}};

export default function Home(){
 const[workflows,setWorkflows]=useState(initial),[selected,setSelected]=useState("All workflows"),[query,setQuery]=useState(""),[reasoning,setReasoning]=useState(false),[details,setDetails]=useState(false),[modal,setModal]=useState(false),[noteOpen,setNoteOpen]=useState(false),[note,setNote]=useState(""),[savedNote,setSavedNote]=useState(""),[toast,setToast]=useState("");
 const searchRef=useRef<HTMLInputElement>(null);const visible=workflows.filter(w=>`${w.name} ${w.team}`.toLowerCase().includes(query.toLowerCase()));const comparison=comparisonData[selected]||comparisonData["All workflows"];const acceptanceDelta=comparison.acceptance[1]-comparison.acceptance[0],reviewDelta=comparison.review[1]-comparison.review[0];
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();searchRef.current?.focus()}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[]);
 const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2200)};
 const exportData=()=>{const csv=["workflow,team,sessions,acceptance,status",...workflows.map(w=>`${w.name},${w.team},${w.sessions},${w.acceptance},${w.status}`)].join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));const a=document.createElement("a");a.href=url;a.download="signaldesk-workflow-health.csv";a.click();URL.revokeObjectURL(url);notify("CSV exported")};
 const addWorkflow=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const data=new FormData(e.currentTarget);const name=String(data.get("name")||"").trim(),team=String(data.get("team")||"").trim();if(!name||!team)return;setWorkflows(v=>[...v,{name,team,sessions:0,acceptance:0,status:"Watch"}]);setModal(false);notify("Workflow added locally")};
 return <main className="shell">
 <section className="workspace" id="top"><header><div className="search">⌕ <input ref={searchRef} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search workflows" aria-label="Search workflows"/><kbd>⌘ K</kbd></div><div className="profile"><span>Aug 1–7, 2026</span><i>DS</i><b>Data Science<br/><small>Product Operations</small></b></div></header>
 <div className="page-head"><div><h1>Workflow Health</h1><p>Plans, priorities, and quality signals for SignalDesk.</p></div><div><button className="primary" onClick={()=>setModal(true)}>＋ Add workflow</button><button onClick={exportData}>Export data</button></div></div>
 <section className="kpis"><article className="featured"><label>Representative sessions <i>↗</i></label><strong>1,167</strong><p>40 clean rows analyzed</p></article><article><label>Completed outputs <i>↗</i></label><strong>898</strong><p>76.9% completion rate</p></article><article><label>Estimated time saved <i>↗</i></label><strong>103.3h</strong><p>Directional estimate</p></article><article><label>Data warnings <i>↗</i></label><strong>5</strong><p>Review before rollout</p></article></section>
 <section className="dashboard-grid"><article className="card analytics" id="analytics"><div className="card-head"><div><h2>What changed after the prompt launch?</h2><p>Aug 1–3 compared with Aug 4–6 · August 7 excluded</p></div><select value={selected} onChange={e=>setSelected(e.target.value)} aria-label="Select workflow comparison"><option>All workflows</option>{initial.map(w=><option key={w.name}>{w.name}</option>)}</select></div><div className="comparison"><div className="period"><small>BEFORE · AUG 1–3</small><strong>{comparison.acceptance[0].toFixed(1)}%</strong><span>output acceptance</span><b>{comparison.review[0].toFixed(1)}% review rate</b></div><div className="change"><span>→</span><strong className={acceptanceDelta>=0?"up":"down"}>{acceptanceDelta>=0?"+":""}{acceptanceDelta.toFixed(1)} pp</strong><small>acceptance change</small></div><div className="period after"><small>AFTER · AUG 4–6</small><strong>{comparison.acceptance[1].toFixed(1)}%</strong><span>output acceptance</span><b>{comparison.review[1].toFixed(1)}% review rate <em className={reviewDelta<=0?"up":"down"}>({reviewDelta>=0?"+":""}{reviewDelta.toFixed(1)} pp)</em></b></div></div><div className="comparison-read"><i>i</i><p><b>Read:</b> {comparison.read}<small>Directional comparison only—not causal. The window is short and there is no control group.</small></p></div></article>
 <article className="card next" id="reviews"><div className="card-head"><div><h2>Investigate next</h2><p>Highest-priority follow-up</p></div><b>High</b></div><h3>Reply draft · August 7</h3><p>Acceptance fell while review flags rose, despite model confidence increasing.</p><dl><div><dt>Acceptance</dt><dd>47.1%</dd></div><div><dt>Review rate</dt><dd>70.6%</dd></div><div><dt>Confidence</dt><dd>.91</dd></div></dl><button className="primary" onClick={()=>setReasoning(v=>!v)}>{reasoning?"Hide":"View"} reasoning →</button>{reasoning&&<div className="reasoning">August 7 is not evidence of model improvement: a mid-day policy change altered review behavior, coverage is incomplete, and confidence moved opposite acceptance.</div>}</article>
 <article className="card workflow-list" id="workflows"><div className="card-head"><div><h2>Workflow scorecard</h2><p>Decision-ready weekly metrics</p></div><button onClick={()=>setNoteOpen(v=>!v)}>＋ Add note</button></div>{noteOpen&&<form className="note-form" onSubmit={e=>{e.preventDefault();setSavedNote(note);setNoteOpen(false);notify("Note saved")}}><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Add a team note…" autoFocus/><button className="primary">Save</button></form>}{savedNote&&<p className="saved-note">Note: {savedNote}</p>}{visible.map(w=><div className="workflow-row" key={w.name}><i>{w.name[0]}</i><div><b>{w.name}</b><small>{w.team} · {w.sessions} sessions</small></div><span>{w.acceptance}%<small>accepted</small></span><em className={w.status.toLowerCase()}>{w.status}</em></div>)}{!visible.length&&<p className="empty">No workflows match “{query}”.</p>}</article>
 <article className="card progress"><div className="card-head"><div><h2>Weekly completion</h2><p>Across representative traffic</p></div><button aria-label="Toggle completion details" onClick={()=>setDetails(v=>!v)}>•••</button></div><div className="donut"><div><strong>76.9%</strong><span>Complete</span></div></div><div className="legend"><span><i/>Completed 898</span><span><i/>Incomplete 269</span></div>{details&&<p className="completion-detail">898 of 1,167 sessions reached a final output. Completion does not guarantee output quality.</p>}</article>
 <article className="card quality" id="quality"><div><h2>Data quality</h2><p>Five issues are disclosed in the analysis.</p></div><ul><li><i>✓</i> Duplicate export removed</li><li><i>✓</i> Demo spike excluded</li><li><i>✓</i> Team casing normalized</li><li><i>!</i> Confidence value missing</li><li><i>!</i> Final-day coverage incomplete</li></ul></article></section></section>
 {modal&&<div className="modal-backdrop" onMouseDown={()=>setModal(false)}><form className="modal" onSubmit={addWorkflow} onMouseDown={e=>e.stopPropagation()}><div><h2>Add a workflow</h2><button type="button" onClick={()=>setModal(false)}>×</button></div><label>Workflow name<input name="name" required autoFocus/></label><label>Team<input name="team" required/></label><button className="primary">Add to scorecard</button></form></div>}{toast&&<div className="toast">{toast}</div>}
 </main>;
}
